### ISSUE TITLE
Using the NPM version with require

### ISSUE THREAD

**Issue by denizdogan** [booncon/slippry#111]
What's the proper way to use the version that's published on NPM?

```console
> require('slippry')
Error: Cannot find module 'slippry'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
```

**Comment by sftsk** [comment]
This is not possible at the moment, Slippry will only work as a jQuery plugin. npm is only used to make it easier to install in different build environment :(

This is high on our ideas for the next big Slippry update,

**Comment by YUzhva** [comment]
@denizdogan 
require('slippry/dist/slippry.min.js');

@sftsk 
just add next line to package.json
`"main": "./dist/slippry.min.js",`

So when the devs would use `require('slippry');` syntax it would import **slippry.min.js ** file.
